acseo_typesense:
    # Typesense host settings
    typesense:
        url: '%env(resolve:TYPESENSE_URL)%'
        key: '%env(resolve:TYPESENSE_KEY)%'
    # Collection settings
    collections:
        posts:                                     # Typesense collection name
            entity: 'App\Entity\Post'              # Doctrine Entity class
            fields: 
                #
                # Keeping Database and Typesense synchronized with ids
                #
                id:                                # Entity attribute name
                    name: id                       # Typesense attribute name
                    type: primary                  # Attribute type
                #
                # Using again id as a sortable field (int32 required)
                #
                sortable_id:
                    entity_attribute: id             # Entity attribute name forced
                    name: sortable_id                # Typesense field name
                    type: int32
                title: 
                    name: title
                    type: string
                information:
                    name: information
                    type: string
                # media:
                #      name: media
                #      type: object                    # Object conversion with __toString()
                # media.filename:
                #     name: media_filename           
                #     type: string
                #     facet: true                      # Declare field as facet (required to use "group_by" query option)
                #     entity_attribute: media.filename # Equivalent of $book->getAuthor()->getCountry()
                created: 
                    name: created
                    type: datetime
                    optional: true                   # Declare field as optional
            default_sorting_field: sortable_id       # Default sorting field. Must be int32 or float
            finders:                                 # Declare your specific finder
                posts_autocomplete:                  # Finder name
                    finder_parameters:               # Parameters used by the finder
                        query_by: title              #
                        limit: 10                    # You can add as key / valuesspecifications
                        prefix: true                 # based on Typesense Request 
                        num_typos: 1                 #
                        drop_tokens_threshold: 1     #