# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle

oneup_flysystem:
    adapters:
        default_adapter:
            local:
                directory: '%kernel.project_dir%/var/storage/default'

        acme.flysystem_adapter:
            awss3v3:
                client: Aws\S3\S3Client
                bucket: '%env(S3_BUCKET)%'
                # prefix: ~

    filesystems:
        media:
            adapter: acme.flysystem_adapter
            alias: League\Flysystem\Filesystem
            mount: s3_filesystem

        local:
            adapter: default_adapter
            alias: League\Flysystem\Filesystem
            mount: local_filesystem