# Read the documentation: https://github.com/1up-lab/OneupUploaderBundle/blob/master/Resources/doc/index.md
oneup_uploader:
    mappings:
        # This is a mapping example, remove it and create your own mappings.
        media:
            frontend: dropzone # or any uploader you use in the frontend
            enable_progress: true

            storage:
                type: flysystem
                filesystem: oneup_flysystem.media_filesystem