version: '3.8'

services:
  web-dp-php-fpm:
    container_name: web-dp-php
    build:
      context: ./php-fpm
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ../:/var/www

  web-dp-nginx:
    container_name: web-dp-nginx
    build:
      context: ./nginx
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${VIRTUAL_HOST}
    volumes:
      - ../:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./logs:/var/log
    depends_on:
      - web-dp-php-fpm
    # If you want to expose port 80 to the host
    # ports:
    #   - "80:80"

networks:
  default:
    name: web
